### ISSUE TITLE
Error: Cannot find module 'BugSnag'

### ISSUE THREAD

**Issue by sn0rcha** [stitchng/adonis-bugsnag#4]
Hey There,

I installed this on a fresh adonis install today, and whenever an error occurs after I created the ehandler like in the readme, I get the following:

```
Error: Cannot find module 'BugSnag'
Error: Cannot find module 'BugSnag'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at requireStack (/var/www/asics/node_modules/require-stack/src/index.js:44:12)
    at Ioc._require (/var/www/asics/node_modules/@adonisjs/fold/src/Ioc/index.js:345:12)
    at Ioc.use (/var/www/asics/node_modules/@adonisjs/fold/src/Ioc/index.js:742:17)
    at Object.<anonymous> (/var/www/asics/app/Exceptions/Handler.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

**Comment by stitchng** [comment]
@sn0rcha so sorry for the late response... This issue was fixed in v0.2.0

I'm closing out now....

Cheers!
